
tiff: read-tiff.cpp
	g++ -o read-tiff read-tiff.cpp -ltiff -L/usr/local/lib/

tiles: read-tiles.cpp
	g++ -o read-tiles read-tiles.cpp -ltiff -L/usr/local/lib/


strips: read-strips.cpp
	g++ -o read-strips read-strips.cpp -ltiff -L/usr/local/lib/


